//! Embedded template strings for SDD/HDD document scaffolding.
//!
//! Each template uses `{{variable_name}}` syntax for substitution.
//! Unresolved variables remain as placeholders for the user/agent to fill in.

/// Template metadata for display and selection.
#[derive(Debug, Clone)]
pub struct TemplateMeta {
    /// Template identifier used in CLI commands (e.g., "constitution")
    pub id: &'static str,
    /// Human-readable name
    pub name: &'static str,
    /// Short description
    pub description: &'static str,
    /// Default output path (relative to project root), may contain `{{var}}` placeholders
    pub default_output: &'static str,
    /// Category: "spec", "harness", or "golden"
    pub category: &'static str,
    /// List of variable names this template expects
    pub variables: &'static [&'static str],
}

/// All available template metadata entries.
pub const TEMPLATES: &[TemplateMeta] = &[
    TemplateMeta {
        id: "constitution",
        name: "Project Constitution",
        description: "Immutable governing principles — rules no agent may violate",
        default_output: "docs/specs/constitution.md",
        category: "spec",
        variables: &["project_name"],
    },
    TemplateMeta {
        id: "spec",
        name: "Feature Specification",
        description: "SDD feature spec with user stories, requirements, and API surface",
        default_output: "docs/specs/spec-{{feature}}.md",
        category: "spec",
        variables: &["feature", "id", "actor", "action", "benefit"],
    },
    TemplateMeta {
        id: "data-model",
        name: "Data Model & Contracts",
        description: "Entity definitions, invariants, database schema, and API contracts",
        default_output: "docs/specs/data-model.md",
        category: "spec",
        variables: &["project_name"],
    },
    TemplateMeta {
        id: "harness",
        name: "Harness Specification",
        description: "HDD test harness with LATS-style trajectories and failure modes",
        default_output: "docs/harness/harness-{{feature}}.md",
        category: "harness",
        variables: &["feature", "id"],
    },
    TemplateMeta {
        id: "playbook",
        name: "Simulation Playbook",
        description: "Multi-agent simulation scenario with CRDT merge verification",
        default_output: "docs/harness/simulation-playbook.md",
        category: "harness",
        variables: &["scenario"],
    },
    TemplateMeta {
        id: "golden",
        name: "Golden Set Evaluation",
        description: "TOML-based evaluation cases with must_contain/must_not_contain checks",
        default_output: ".hief/golden/{{name}}.toml",
        category: "golden",
        variables: &["name", "description"],
    },
];

// ---------------------------------------------------------------------------
// Embedded template content
// ---------------------------------------------------------------------------

pub const CONSTITUTION_TEMPLATE: &str = r#"# Project Constitution: {{project_name}}

## Identity
- **Name:** {{project_name}}
- **Purpose:** {{purpose}}
- **Architecture:** {{architecture}}

## Inviolable Rules

### Code Quality
- [ ] All public functions must have doc comments
- [ ] No `.unwrap()` in production code paths (use `?` or `expect()` with context)
- [ ] All error types must implement `std::error::Error`
- [ ] No `unsafe` blocks without documented safety invariants

### Architecture
- [ ] {{arch_rule_1}}
- [ ] {{arch_rule_2}}
- [ ] {{arch_rule_3}}
- [ ] {{arch_rule_4}}

### Dependencies
- [ ] Minimize dependency count; prefer stdlib + established crates
- [ ] Pin versions for grammar/parser crates to avoid `cc` conflicts
- [ ] Async runtime: tokio (not async-std)

### Process
- [ ] Every change must trace to an approved intent
- [ ] No agent may approve its own intent
- [ ] Golden set regressions block merge

## Anti-Patterns (Never Do This)
- {{anti_pattern_1}}
- {{anti_pattern_2}}
- {{anti_pattern_3}}
- {{anti_pattern_4}}

---

*Generated by `hief docs generate constitution`. Review and customize before approving.*
"#;

pub const SPEC_TEMPLATE: &str = r#"# Feature Spec: {{feature}}

**Intent:** hief-{{id}}
**Status:** draft
**Priority:** {{priority}}

## Overview
{{overview}}

## User Stories

### US-1: {{story_title_1}}
**As a** {{actor}},
**I want to** {{action}},
**So that** {{benefit}}.

**Acceptance Criteria:**
- Given {{precondition_1}}, When {{action_1}}, Then {{expected_1}}
- Given {{precondition_2}}, When {{action_2}}, Then {{expected_2}}

### US-2: {{story_title_2}}
**As a** {{actor}},
**I want to** {{action_alt}},
**So that** {{benefit_alt}}.

**Acceptance Criteria:**
- Given {{precondition_3}}, When {{action_3}}, Then {{expected_3}}

## Functional Requirements

| ID | Requirement | Source File | Status |
|----|------------|-------------|--------|
| FR-001 | {{req_1}} | `src/{{source_1}}` | ⬜ Not started |
| FR-002 | {{req_2}} | `src/{{source_2}}` | ⬜ Not started |
| FR-003 | {{req_3}} | `src/{{source_3}}` | ⬜ Not started |

## API Surface

```rust
// Key public functions/types for this feature
{{api_surface}}
```

## Dependencies
- Depends on: {{depends_on}}
- Blocked by: {{blocked_by}}

## Quality Criteria
- Must contain: {{must_contain}}
- Must not contain: {{must_not_contain}}

## Notes
- {{note_1}}
- {{note_2}}

---

*Generated by `hief docs generate spec`. Review and customize before approving.*
"#;

pub const DATA_MODEL_TEMPLATE: &str = r#"# Data Model: {{project_name}}

## Core Entities

### {{entity_1}}
```rust
// From src/{{entity_1_path}}
pub struct {{entity_1}} {
    {{entity_1_fields}}
}
```

**Invariants:**
- {{entity_1_invariant_1}}
- {{entity_1_invariant_2}}

**Transitions:**
```
{{entity_1_transitions}}
```

### {{entity_2}}
```rust
// From src/{{entity_2_path}}
pub struct {{entity_2}} {
    {{entity_2_fields}}
}
```

**Invariants:**
- {{entity_2_invariant_1}}
- {{entity_2_invariant_2}}

## Database Schema

### Table: {{table_1}}
| Column | Type | Constraints | Notes |
|--------|------|-------------|-------|
| id | TEXT | PRIMARY KEY | {{id_format}} |
| {{col_1}} | {{type_1}} | {{constraint_1}} | {{note_col_1}} |
| {{col_2}} | {{type_2}} | {{constraint_2}} | {{note_col_2}} |

### Table: {{table_2}}
| Column | Type | Constraints | Notes |
|--------|------|-------------|-------|
| {{col_3}} | {{type_3}} | {{constraint_3}} | {{note_col_3}} |

## API Contracts

### MCP Tool: {{tool_name_1}}
- **Input:** `{{tool_input_1}}`
- **Output:** JSON string of `{{tool_output_1}}`
- **Errors:** `{{tool_errors_1}}`

### MCP Tool: {{tool_name_2}}
- **Input:** `{{tool_input_2}}`
- **Output:** JSON string of `{{tool_output_2}}`
- **Errors:** `{{tool_errors_2}}`

---

*Generated by `hief docs generate data-model`. Review and customize before approving.*
"#;

pub const HARNESS_TEMPLATE: &str = r#"# Harness Specification: {{feature}}

**Intent:** hief-{{id}}
**Type:** {{harness_type}}

## Purpose
{{purpose}}

## Environment Requirements
- [ ] In-memory database (no filesystem side effects)
- [ ] {{env_req_1}}
- [ ] {{env_req_2}}

## Scenario: {{scenario_name}}

### Setup
```rust
// Code to initialize the harness environment
let db = Database::open_memory().await?;
let tmp = tempfile::tempdir()?;
{{setup_code}}
```

### Execution Steps (LATS Trajectory)

| Step | Action | Expected State | Validation |
|------|--------|---------------|------------|
| 1 | {{step_1_action}} | {{step_1_state}} | {{step_1_validation}} |
| 2 | {{step_2_action}} | {{step_2_state}} | {{step_2_validation}} |
| 3 | {{step_3_action}} | {{step_3_state}} | {{step_3_validation}} |
| 4 | {{step_4_action}} | {{step_4_state}} | {{step_4_validation}} |

### Success Criteria
- [ ] All steps complete without panic
- [ ] Database state matches expectations at each step
- [ ] No resource leaks (temp dirs cleaned up)
- [ ] Execution completes within {{timeout}}

### Failure Modes & Recovery

| Failure | Detection | Recovery |
|---------|-----------|----------|
| {{failure_1}} | {{detection_1}} | {{recovery_1}} |
| {{failure_2}} | {{detection_2}} | {{recovery_2}} |

## Cleanup
```rust
// Resources to release
drop(db);
tmp.close()?;
```

---

*Generated by `hief docs generate harness`. Review and customize before approving.*
"#;

pub const PLAYBOOK_TEMPLATE: &str = r#"# Simulation Playbook: {{scenario}}

## Agents Involved
| Agent | Role | Fork Point |
|-------|------|-----------|
| {{agent_1}} | {{agent_1_role}} | CRDT fork from main |
| {{agent_2}} | {{agent_2_role}} | CRDT fork from main |
| Human | Reviews and approves | N/A |

## Timeline

```
T=0:   Both agents fork the CRDT document
T=1:   {{agent_1}} — {{t1_action}}
T=2:   {{agent_2}} — {{t2_action}}
T=3:   {{t3_action}}
T=4:   {{t4_action}}
T=5:   CRDT merge: {{agent_1}} ← {{agent_2}}
T=6:   Verify: {{t6_verify}}
T=7:   {{t7_action}}
T=8:   Verify: {{t8_verify}}
```

## Invariants to Verify After Merge
- [ ] Both agents' intents exist in merged document
- [ ] Edge relationships are preserved
- [ ] Status updates from both agents are reflected
- [ ] Actor IDs are distinct
- [ ] Change count increases monotonically
- [ ] {{custom_invariant_1}}
- [ ] {{custom_invariant_2}}

---

*Generated by `hief docs generate playbook`. Review and customize before approving.*
"#;

pub const GOLDEN_TEMPLATE: &str = r#"[metadata]
name = "{{name}}"
description = "{{description}}"

[[cases]]
id = "{{case_1_id}}"
name = "{{case_1_name}}"
priority = "high"
[cases.checks]
must_not_contain = [{{case_1_must_not_contain}}]
file_patterns = ["src/**/*.rs"]

[[cases]]
id = "{{case_2_id}}"
name = "{{case_2_name}}"
priority = "critical"
[cases.checks]
must_contain = [{{case_2_must_contain}}]
file_patterns = ["src/**/*.rs"]

[[cases]]
id = "{{case_3_id}}"
name = "{{case_3_name}}"
priority = "medium"
[cases.checks]
must_not_contain = [{{case_3_must_not_contain}}]
file_patterns = ["src/**/*.rs"]
"#;

/// Look up a template's content by its ID.
pub fn get_template_content(id: &str) -> Option<&'static str> {
    match id {
        "constitution" => Some(CONSTITUTION_TEMPLATE),
        "spec" => Some(SPEC_TEMPLATE),
        "data-model" => Some(DATA_MODEL_TEMPLATE),
        "harness" => Some(HARNESS_TEMPLATE),
        "playbook" => Some(PLAYBOOK_TEMPLATE),
        "golden" => Some(GOLDEN_TEMPLATE),
        _ => None,
    }
}

/// Look up template metadata by its ID.
pub fn get_template_meta(id: &str) -> Option<&'static TemplateMeta> {
    TEMPLATES.iter().find(|t| t.id == id)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_templates_have_content() {
        for meta in TEMPLATES {
            assert!(
                get_template_content(meta.id).is_some(),
                "Template '{}' has metadata but no content",
                meta.id
            );
        }
    }

    #[test]
    fn test_template_meta_lookup() {
        assert!(get_template_meta("constitution").is_some());
        assert!(get_template_meta("spec").is_some());
        assert!(get_template_meta("data-model").is_some());
        assert!(get_template_meta("harness").is_some());
        assert!(get_template_meta("playbook").is_some());
        assert!(get_template_meta("golden").is_some());
        assert!(get_template_meta("nonexistent").is_none());
    }

    #[test]
    fn test_template_content_contains_variables() {
        let content = get_template_content("constitution").unwrap();
        assert!(content.contains("{{project_name}}"));
    }

    #[test]
    fn test_template_count_matches() {
        assert_eq!(TEMPLATES.len(), 6);
    }
}
