//! Semantic vector search via LanceDB.
//!
//! This module provides embedded vector storage and ANN similarity search
//! for code chunks. It complements the FTS5 keyword search in [`search`]
//! and the structural pattern search in [`structural`].
//!
//! # Architecture
//!
//! ```text
//! Code chunks ──► Embeddings ──► LanceDB (.hief/vectors/)
//!                                    │
//!                     semantic_search ◄──── MCP tool
//! ```
//!
//! Embeddings are generated by the host agent's LLM (via a callback) or
//! by a local model. HIEF itself does not bundle an LLM.

#![allow(dead_code)]

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use tracing::{info, warn};

use crate::errors::Result;

/// Configuration for the vector search subsystem.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VectorConfig {
    /// Whether vector search is enabled (default: false).
    #[serde(default)]
    pub enabled: bool,
    /// Embedding dimensions (default: 384 for small models, 768/1536 for larger).
    #[serde(default = "default_dimensions")]
    pub dimensions: usize,
    /// Distance metric: "cosine" (default) or "l2".
    #[serde(default = "default_metric")]
    pub metric: String,
}

impl Default for VectorConfig {
    fn default() -> Self {
        Self {
            enabled: false,
            dimensions: default_dimensions(),
            metric: default_metric(),
        }
    }
}

fn default_dimensions() -> usize {
    384
}

fn default_metric() -> String {
    "cosine".to_string()
}

/// A code chunk with its embedding vector.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddedChunk {
    /// Chunk ID (matches the chunk in libsql).
    pub chunk_id: String,
    /// File path relative to project root.
    pub file_path: String,
    /// Symbol name (if extracted from AST).
    pub symbol_name: Option<String>,
    /// Language of the source file.
    pub language: String,
    /// The embedding vector.
    pub vector: Vec<f32>,
}

/// Result of a semantic search query.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SemanticResult {
    /// Chunk ID.
    pub chunk_id: String,
    /// File path relative to project root.
    pub file_path: String,
    /// Symbol name if available.
    pub symbol_name: Option<String>,
    /// Language.
    pub language: String,
    /// Code content of the chunk.
    pub content: String,
    /// Similarity score (0.0 - 1.0, higher is more similar).
    pub score: f32,
}

/// Semantic search query parameters.
#[derive(Debug, Clone)]
pub struct SemanticQuery {
    /// The query text (will be embedded before searching).
    pub query: String,
    /// Max results to return.
    pub top_k: usize,
    /// Optional language filter.
    pub language: Option<String>,
}

impl SemanticQuery {
    pub fn new(query: &str) -> Self {
        Self {
            query: query.to_string(),
            top_k: 10,
            language: None,
        }
    }
}

/// Returns the path to the LanceDB vectors directory.
pub fn vectors_dir(project_root: &Path) -> PathBuf {
    project_root.join(".hief").join("vectors")
}

/// Initialize the vector store. Creates the LanceDB directory and table
/// if they don't exist.
pub async fn init(project_root: &Path, config: &VectorConfig) -> Result<()> {
    if !config.enabled {
        info!("Vector search is disabled in configuration");
        return Ok(());
    }

    let dir = vectors_dir(project_root);
    if !dir.exists() {
        std::fs::create_dir_all(&dir)?;
        info!("Created vector store directory: {}", dir.display());
    }

    // TODO: Initialize LanceDB connection and create table schema
    // let db = lancedb::connect(dir.to_str().unwrap()).execute().await?;
    // db.create_empty_table("code_chunks", schema).execute().await?;

    info!(
        "Vector store initialized (dimensions={}, metric={})",
        config.dimensions, config.metric
    );
    Ok(())
}

/// Store embeddings for a batch of code chunks.
///
/// This is called after the index build phase, once embeddings have been
/// generated for new/updated chunks.
pub async fn store_embeddings(
    project_root: &Path,
    chunks: &[EmbeddedChunk],
    _config: &VectorConfig,
) -> Result<usize> {
    if chunks.is_empty() {
        return Ok(0);
    }

    let _dir = vectors_dir(project_root);

    // TODO: Implement LanceDB storage
    // let db = lancedb::connect(dir.to_str().unwrap()).execute().await?;
    // let table = db.open_table("code_chunks").execute().await?;
    // table.add(chunks_to_records(chunks)).execute().await?;

    warn!(
        "Vector storage not yet implemented — {} chunks would be stored",
        chunks.len()
    );
    Ok(chunks.len())
}

/// Search for code chunks semantically similar to the query.
///
/// The query text must first be embedded using the same model that
/// generated the stored embeddings. The caller provides the query vector.
pub async fn search(
    project_root: &Path,
    query_vector: &[f32],
    query: &SemanticQuery,
    _config: &VectorConfig,
) -> Result<Vec<SemanticResult>> {
    let _dir = vectors_dir(project_root);

    // TODO: Implement LanceDB ANN search
    // let db = lancedb::connect(dir.to_str().unwrap()).execute().await?;
    // let table = db.open_table("code_chunks").execute().await?;
    // let results = table.vector_search(query_vector)
    //     .limit(query.top_k)
    //     .execute()
    //     .await?;

    warn!(
        "Semantic search not yet implemented (query='{}', top_k={}, language={:?}, vector_dims={})",
        query.query,
        query.top_k,
        query.language,
        query_vector.len()
    );
    Ok(Vec::new())
}

/// Delete all embeddings for files that are no longer in the index.
pub async fn prune_deleted(
    project_root: &Path,
    deleted_file_paths: &[String],
    _config: &VectorConfig,
) -> Result<usize> {
    if deleted_file_paths.is_empty() {
        return Ok(0);
    }

    let _dir = vectors_dir(project_root);

    // TODO: Implement LanceDB deletion
    // let db = lancedb::connect(dir.to_str().unwrap()).execute().await?;
    // let table = db.open_table("code_chunks").execute().await?;
    // for path in deleted_file_paths {
    //     table.delete(&format!("file_path = '{}'", path)).execute().await?;
    // }

    warn!(
        "Vector pruning not yet implemented — {} files would be pruned",
        deleted_file_paths.len()
    );
    Ok(deleted_file_paths.len())
}

/// Get statistics about the vector store.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VectorStats {
    pub total_embeddings: usize,
    pub dimensions: usize,
    pub metric: String,
    pub store_size_bytes: u64,
}

pub async fn stats(project_root: &Path, config: &VectorConfig) -> Result<VectorStats> {
    let dir = vectors_dir(project_root);
    let store_size = if dir.exists() { dir_size(&dir) } else { 0 };

    Ok(VectorStats {
        total_embeddings: 0, // TODO: query LanceDB for count
        dimensions: config.dimensions,
        metric: config.metric.clone(),
        store_size_bytes: store_size,
    })
}

/// Calculate total size of a directory.
fn dir_size(path: &Path) -> u64 {
    let mut total = 0u64;
    if let Ok(entries) = std::fs::read_dir(path) {
        for entry in entries.flatten() {
            let metadata = entry.metadata();
            if let Ok(meta) = metadata {
                if meta.is_file() {
                    total += meta.len();
                } else if meta.is_dir() {
                    total += dir_size(&entry.path());
                }
            }
        }
    }
    total
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_default_config() {
        let config = VectorConfig::default();
        assert!(!config.enabled);
        assert_eq!(config.dimensions, 384);
        assert_eq!(config.metric, "cosine");
    }

    #[test]
    fn test_semantic_query() {
        let query = SemanticQuery::new("authentication logic");
        assert_eq!(query.query, "authentication logic");
        assert_eq!(query.top_k, 10);
        assert!(query.language.is_none());
    }

    #[test]
    fn test_vectors_dir() {
        let dir = vectors_dir(Path::new("/tmp/project"));
        assert_eq!(dir, PathBuf::from("/tmp/project/.hief/vectors"));
    }

    #[tokio::test]
    async fn test_init_disabled() {
        let config = VectorConfig::default(); // enabled = false
        let tmp = tempfile::tempdir().unwrap();
        let result = init(tmp.path(), &config).await;
        assert!(result.is_ok());
        // Should not create directory when disabled
        assert!(!vectors_dir(tmp.path()).exists());
    }

    #[tokio::test]
    async fn test_init_enabled() {
        let config = VectorConfig {
            enabled: true,
            ..Default::default()
        };
        let tmp = tempfile::tempdir().unwrap();
        let result = init(tmp.path(), &config).await;
        assert!(result.is_ok());
        assert!(vectors_dir(tmp.path()).exists());
    }

    #[tokio::test]
    async fn test_search_empty() {
        let config = VectorConfig::default();
        let tmp = tempfile::tempdir().unwrap();
        let query = SemanticQuery::new("test");
        let results = search(tmp.path(), &[], &query, &config).await.unwrap();
        assert!(results.is_empty());
    }
}
